services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: cosmos
      POSTGRES_PASSWORD: odyssey
      POSTGRES_DB: cosmos_odyssey
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: